version: '3'

vars:
  PROTOC_GEN_GO_VERSION: 'v1.36.11'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.6.1'
  BUF_VERSION: '1.66.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  BUF: '{{.BIN_DIR}}/buf'

tasks:
  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        [ -f {{.BUF}} ] || {
          mkdir -p {{.BIN_DIR}} tmp-buf
          curl -sSL \
            "https://github.com/bufbuild/buf/releases/download/v{{.BUF_VERSION}}/buf-$(uname -s)-$(uname -m).tar.gz" \
            | tar -xz -C tmp-buf
          mv tmp-buf/buf/bin/buf {{.BUF}}
          rm -rf tmp-buf
          chmod +x {{.BUF}}
        }

  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }

  proto:lint:
    deps: [ install-buf, proto:install-plugins ]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: api/proto
    cmds:
      - '{{.BUF}} lint'

  proto:gen:
    deps: [ install-buf, proto:install-plugins, proto:lint ]
    desc: Генерация Go-кода из .proto
    dir: api/proto
    cmds:
      - '{{.BUF}} generate'